source_dir = "/home/bebop831/Dev/serv"
target_dir = "/home/bebop831/Dev/filo_target"
log_file = "/home/bebop831/Dev/filo/filo.log"
max_fill = 0.95
log_level = "info"
sync_delay = "5s"
max_openfile = 1000
approved_extensions = ['.mkv', '.mp4', '.txt']

