source_dir = "/home/bebop831/Dev/serv"
SourceDir = "/home/bebop831/Dev/serv"
target_dir = "/home/bebop831/Dev/filo_target"
TargetDir = "/home/bebop831/Dev/filo_target"
log_file = "/Users/bebop831/Dev/filo/filo.log"
LogFile = "/Users/bebop831/Dev/filo/filo.log"
max_fill = 0.95
MaxFill = 0.95
LogLevel = "debug"
log_level = "debug"
SyncDelay = "5s"
sync_delay = "5s"
ApprovedExtensions = [".mkv", ".mp4", ".txt"]
approved_extensions = [".mkv", ".mp4", ".txt"]
max_openfile = 100
MaxOpenFile = 100